name: one_projects
description: Map and sync your 1 password projects respectively.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pluto_menu_bar: ^3.0.1
  get: ^4.6.5
  flutter_svg: ^2.0.7
  icons_launcher: ^2.1.1
  google_fonts: ^5.1.0
  timeago: ^3.4.0
  flutter_markdown: ^0.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    linux:
      enable: true
    windows:
      enable: true
    macos:
      enable: true
